### ISSUE TITLE
Replacement robustness

### ISSUE THREAD

**Issue by cyrilchapon** [mars/heroku-js-runtime-env-buildpack#4]
Hey :)

Thanks for this great lib 😀. Two questions :

1) Why do you replace the placeholder with a JSON string, instead of directly doing it with a JS object, [here](https://github.com/mars/heroku-js-runtime-env-buildpack/blob/master/lib/injectable_env.rb#L11-L18) ?

This enforces [parsing and testing here](https://github.com/mars/heroku-js-runtime-env/blob/master/index.js#L24-L33)

2) see [here](https://github.com/mars/heroku-js-runtime-env/issues/10)

**Comment by mars** [comment]
We have no idea what people will try to put in env vars. So, the injected data is defensively coded to avoid problems with this bundle altering technique.

By using JSON, parsing of the data injected into the bundle happens when the `runtimeEnv()` function is invoked.

If the injected data was a plain JavaScript object, then parsing errors would happen as the bundle is parsed by the browser, possibly throwing an error that would prevent the whole bundle from loading, crippling or killing the app.
